# Generated by Django 4.2.7 on 2023-11-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_history_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='obid',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
